#:schema node_modules/wrangler/config-schema.json
name = "sublink-wk"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "3a633a4719e34e1a9889b302ad683a58" }
]

[assets]
directory = "./public"
